### ISSUE TITLE
npm start wants npm run first

### ISSUE THREAD

**Issue by omenking** [elthrasher/planetstack#1]
When following the readme it suggest to run `npm start` which then prompts for running `npm run deploy`

![image](https://user-images.githubusercontent.com/7776/129097601-63eb1973-1ec2-4f9f-b772-4176f1361935.png)

**Comment by omenking** [comment]
npm run deploy wants me to run cdk boostrap

![image](https://user-images.githubusercontent.com/7776/129097736-47799048-c3f2-4b49-a4ec-fc4968a5d5f8.png)

**Comment by omenking** [comment]
My CDK is out of date

> This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 9.0.0, but found 13.0.0)

Going to update my CDK

```
npm install -g aws-cdk@latest
```

**Comment by omenking** [comment]
![image](https://user-images.githubusercontent.com/7776/129099462-f4450531-b5b0-41b7-abea-2e75ef4ccae4.png)

> CloudWatch Logs role ARN must be set in account settings to enable logging

hmmm

**Comment by omenking** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/

Looks like the Role is part of the CloudFormation template that is generated so uncertain about its complaint.
 ```
  CWRole7EC94C1E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatch
 ```

![image](https://user-images.githubusercontent.com/7776/129102600-4bd526e5-6ba0-421e-862d-d7e64e2feae3.png)
